name: PHP Tests

on: [push]

jobs:
  test_latest:
    name: Test with PHP Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'
          
      - name: Display files in directory
        run: ls
      
      - name: Start of test
        run: echo "Debut de test"
      
      - name: Display VM
        run: echo "VM"
      
      - name: Display PHP version
        run: php -v

  t1_latest:
    name: Test 1 with PHP 8.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Execute PHP script
        run: php test.php




